build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - command: phpcs-run
                      use_website_config: true
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --bootstrap ./tests/bootstrap.php ./tests --coverage-clover build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "tests/"

